In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from src.models.knn import Knn
from src.models.similarities import perfiles_similarity
import matplotlib.pyplot as plt
import pickle

In [3]:
perfiles = pd.read_parquet('../data/processed/perfiles_sqr_knn.parquet')
perfiles_sqr = pd.read_parquet('../data/processed/perfiles_sqr_filtrado.parquet')

In [4]:
knn = Knn(k=11, weights=np.ones(4)*0.25)

knn.fit(perfiles[['altura', 'peso', 'posicion', 'sexo']].values, perfiles["presiones"].values, perfiles["sqr"].values)

In [5]:
knn.neighbours

array([[   53, 14840,    49, ..., 14220, 14205,    30],
       [14059,    42,    44, ..., 13900,    70,    72],
       [ 4230, 17124, 14217, ...,   165,  8600, 11763],
       ...,
       [13129, 14595, 14596, ..., 10092, 14158, 14159],
       [18227, 21217, 18094, ..., 12033, 14161,  9822],
       [21081, 21030, 20842, ..., 13829, 13828, 13827]])

In [6]:
perfiles

presiones  altura   peso        sqr  posicion  sexo
22217    122232   178.0   75.0  83.008680         0     1
22268    023321   162.0   75.0  70.773244         0     0
22361    122232   180.0   70.0  70.144818         0     1
22362    023111   160.0   50.0  87.152947         0     0
22387    023321   162.0   75.0  81.126354         0     0
...         ...     ...    ...        ...       ...   ...
84990    122222   167.0   58.0  71.508019         1     1
84994    022211   157.0   57.0  56.875936         0     0
84997    022211   157.0   57.0  71.011566         0     0
85001    023321   170.0   80.0  99.304167         0     1
85008    233343   195.0  100.0  55.600643         0     1

[21219 rows x 6 columns]

In [7]:
perfiles.loc[22217, ['altura', 'peso', 'posicion', 'sexo']].values

array([178.0, 75.0, 0, 1], dtype=object)

In [8]:
pred, neigbours = knn.predict(perfiles.loc[22217, ['altura', 'peso', 'posicion', 'sexo']].values, True, False)

In [9]:
knn.ref[neigbours]

array([[65.98134492, 93.20951211, 65.99530992, 87.20077405, 78.59440703,
        82.92540377, 77.95684388, 77.40713213, 89.09445439, 88.82032828,
        91.59429859]])

In [10]:
knn.target

array(['122232', '023321', '122232', ..., '022211', '023321', '233343'],
      dtype=object)